name: EasyTime CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - feature/*
    tags:
        - 'v[0-9]+\.[0-9]+\.[0-9]+' # regex en espérant que github actions accepte cette regex
  workflow_dispatch:

jobs:
  # Job for testing the project
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Run tests
      run:  dotnet test --verbosity normal

  # Job for publishing to NuGet
  publish:
    runs-on: ubuntu-latest
    needs: test                    # Only run if test job is successful
    if: startsWith(github.event.ref, 'refs/tags/v')

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool --version 6.1.0

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}

    - name: Pack NuGet package
      run: dotnet pack -c Release -o ./output /p:PackageVersion=${{ env.RELEASE_VERSION }}

    - name: Publish to NuGet
      run: dotnet nuget push ./output/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json


